name: Build multiplatform executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build Windows Executable
        run: pyinstaller ledsup.spec
      - uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/ledsup.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build Linux Executable
        run: pyinstaller ledsup.spec
      - uses: actions/upload-artifact@v4
        with:
          name: linux-bin
          path: dist/ledsup

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build macOS Executable
        run: pyinstaller ledsup.spec
      - uses: actions/upload-artifact@v4
        with:
          name: macos-bin
          path: dist/ledsup
